site_name: Mozgókép és animációtervező képesítő vizsga
site_description: Művészettörténet és szaktörténet tételek kidolgozva
site_url: https://boriiza.github.io/anim-vizsga-2025/
repo_url: https://github.com/boriiza/anim-vizsga-2025
repo_name: boriiza/anim-vizsga-2025

theme:
  name: material
  language: hu
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.share
    - toc.integrate
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/weather-night
        name: Sötét mód
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Világos mód

nav:
  - Kezdőlap: index.md
  - Művtöri:
    - 1A - Ókori Egyiptom: muvtori/01_A_egyiptom.md
    - 2A - Ókori Görögország: muvtori/02_A_gorog.md
    - 3A - Ókori Róma: muvtori/03_A_romai.md
    - 4A - Ókeresztény és bizánci művészet: muvtori/04_A_kereszteny.md
    - 5A - Román stílus építészete és művészete: muvtori/05_A_roman.md
    - 6A - A gótika építészete: muvtori/06_A_gotika.md
    - 7A - A gótikus szobrászat, festészet és kézművesség: muvtori/07_A_gotika2.md
    - 8A - Az itáliai reneszánsz: muvtori/08_A_reneszasz.md
    - 9A - A reneszánsz Itálián kívül: muvtori/09_A_reneszasz2.md
    - 10A - A barokk építészet és szobrászat: muvtori/10_A_barokk.md
    - 11A - A barokk és rokokó festészet: muvtori/11_A_barokk2.md
    - 12A - A klasszicizmus: muvtori/12_A_klasszicista.md
    - 13A - A romantika, historizmus és eklektika: muvtori/13_A_romantika.md
    - 14A - Az impresszionizmus és posztimpresszionizmus: muvtori/14_A_impresszionizmus.md
    - 15A - A szimbolizmus és szecesszió: muvtori/15_A_szimbolizmus.md
    - 16A - A 20. század eleji avantgárd: muvtori/16_A_avantgard.md
    - 17A - Futurizmus, konstruktivizmus, dadaizmus és szürrealizmus: muvtori/17_A_avantgard2.md
    - 18A - A 20. századi építészet és iparművészet: muvtori/18_A_bauhaus.md
    - 19A - A 20. századi képzőművészet: muvtori/19_A_expresszionizmus.md
    - 20A - A kortárs művészet és a 21. század: muvtori/20_A_kortars.md
  - Szaktöri:
    - 1. tétel: szaktori/01_tetel.md
    - 2. tétel: szaktori/02_tetel.md
    - 3. tétel: szaktori/03_tetel.md
    - 4. tétel: szaktori/04_tetel.md
    - 5. tétel: szaktori/05_tetel.md
    - 6. tétel: szaktori/06_tetel.md
    - 7. tétel: szaktori/07_tetel.md
    - 8. tétel: szaktori/08_tetel.md
    - 9. tétel: szaktori/09_tetel.md
    - 10. tétel: szaktori/10_tetel.md
    - 11. tétel: szaktori/11_tetel.md
    - 12. tétel: szaktori/12_tetel.md
    - 13. tétel: szaktori/13_tetel.md
    - 14. tétel: szaktori/14_tetel.md
    - 15. tétel: szaktori/15_tetel.md
    - 16. tétel: szaktori/16_tetel.md
    - 17. tétel: szaktori/17_tetel.md
    - 18. tétel: szaktori/18_tetel.md
    - 19. tétel: szaktori/19_tetel.md
    - 20. tétel: szaktori/20_tetel.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.superfences
  - mdx_truly_sane_lists

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/boriiza
      name: GitHub
