site_name: Mozgókép és animációtervező képesítő vizsga
site_description: Művészettörténet és szaktörténet tételek kidolgozva
site_url: https://boriiza.github.io/anim-vizsga-2025/
repo_url: https://github.com/boriiza/anim-vizsga-2025
repo_name: boriiza/anim-vizsga-2025

theme:
  name: material
  language: hu
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.share
    - toc.integrate
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/weather-night
        name: Sötét mód
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Világos mód

nav:
  - Kezdőlap: index.md
  - Művtöri:
    - 1A - Ókori Egyiptom: muvtori/01_A_egyiptom.md
    - 2A - Ókori Görögország: muvtori/02_A_gorog.md
    - 3A - Ókori Róma: muvtori/03_A_romai.md
    - 4A - Ókeresztény és bizánci művészet: muvtori/04_A_kereszteny.md
    - 5A - Román stílus építészete és művészete: muvtori/05_A_roman.md
    - 6A - A gótika építészete: muvtori/06_A_gotika.md
    - 7A - A gótikus szobrászat, festészet és kézművesség: muvtori/07_A_gotika2.md
    - 8A - Az itáliai reneszánsz: muvtori/08_A_reneszasz.md
    - 9A - A reneszánsz Itálián kívül: muvtori/09_A_reneszasz2.md
    - 10A - A barokk építészet és szobrászat: muvtori/10_A_barokk.md
    - 11A - A barokk és rokokó festészet: muvtori/11_A_barokk2.md
    - 12A - A klasszicizmus: muvtori/12_A_klasszicista.md
    - 13A - A romantika, historizmus és eklektika: muvtori/13_A_romantika.md
    - 14A - Az impresszionizmus és posztimpresszionizmus: muvtori/14_A_impresszionizmus.md
    - 15A - A szimbolizmus és szecesszió: muvtori/15_A_szimbolizmus.md
    - 16A - A 20. század eleji avantgárd: muvtori/16_A_avantgard.md
    - 17A - Futurizmus, konstruktivizmus, dadaizmus és szürrealizmus: muvtori/17_A_avantgard2.md
    - 18A - A 20. századi építészet és iparművészet: muvtori/18_A_bauhaus.md
    - 19A - A 20. századi képzőművészet: muvtori/19_A_expresszionizmus.md
    - 20A - A kortárs művészet és a 21. század: muvtori/20_A_kortars.md
  - Szaktöri:
    - 1B - Magyar animáció kezdeteitől az 1980-as évekig: szaktori/01_B_magyaranimacio.md
    - 2B - Magyar animáció 1980-as évek utáni története: szaktori/02_B_magyaranimacio_80as_utani.md
    - 3B - Nemzetközi animáció története: szaktori/03_B_nemzetkozi_animacio.md
    - 4B - Mozgóképi formanyelv: szaktori/04_B_mozgokepi_formanyelv.md
    - 5B - Forgatókönyvírás: szaktori/05_B_forgatokonyviras.md
    - 6B - Filmtámogatási pályázat: szaktori/06_B_filmtamogatasi_palyazat.md
    - 7B - Rajzanimáció technika: szaktori/07_B_rajzanimacio_technika.md
    - 8B - Dokumentumfilm forgatás alföldi tanyavilágban: szaktori/08_B_forgatas.md
    - 9B - Bábanimációs technika: szaktori/09_B_babanimacio_technika.md
    - 10B - Kis költségvetésű rövid játékfilm műtermi felvétele: szaktori/10_B_vilagitas.md
    - 11B - Road movie hangfelvétel: szaktori/11_B_hangok.md
    - 12B - Számítógép hardver konfiguráció mozgóképi munkához: szaktori/12_B_szamitogep.md
    - 13B - 3D karaktermodellezés számítógépes játékhoz: szaktori/13_B_3d_animacio_technika.md
    - 14B - 3D printelés animációs alkalmazásai: szaktori/14_B_bab.md
    - 15B - Augmented Reality történelmi épületekhez: szaktori/15_B_AR.md
    - 16B - Zenei fesztivál panorámavideó: szaktori/16_B_panorama.md
    - 17B - Videomapping fesztivál nyitóeseményre: szaktori/17_B_videomapping.md
    - 18B - Virtuális karakter és zöld háttér technika: szaktori/18_B_zoldhatter.md
    - 19B - Díszletkiegészítés (Set Extension) történelmi tévéfilmsorozathoz: szaktori/19_B_diszletkiegeszites.md
    - 20B - 3D fizikai szimulációk vs makettfelvételes technika: szaktori/20_B_vfx_3d_szimulacio.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.superfences
  - mdx_truly_sane_lists

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/boriiza
      name: GitHub
